In [5]:
import psycopg2
import pandas as pd
host = '127.0.0.1'
user = 'postgres'
password = '1234'
database = 'postgres'
port = '5432'

In [4]:
conn = psycopg2.connect(
    host=host,
    user=user,
    password=password,
    database=database,
    port=port
)

cursor = conn.cursor()
cursor.execute('SELECT version()')
record = cursor.fetchone()
print('You are connected to - ', record, '\n')
#close the connection
conn.close()

You are connected to -  ('PostgreSQL 16.11, compiled by Visual C++ build 1944, 64-bit',)

In [6]:
df_user = pd.read_csv('users.csv')
df_events = pd.read_csv('events.csv')
df_urls = pd.read_csv('urls.csv')

In [7]:
df_user

      id        username                       email           created_at
0      1    warmmeadow94     warmmeadow94@seeded.app  2024-10-28 04:53:11
1      2  proudjourney15  proudjourney15@opswise.net  2025-09-15 13:11:10
2      3    opalgarden81    opalgarden81@opswise.net  2024-09-08 10:51:27
3      4   silvertrail28   silvertrail28@example.com  2025-10-29 16:56:24
4      5     opalorbit02     opalorbit02@example.com  2024-03-17 22:01:14
..   ...             ...                         ...                  ...
395  396    ambertrail34       ambertrail34@acme.dev  2025-01-03 16:16:38
396  397   youngkernel05   youngkernel05@relay.cloud  2024-10-23 11:58:07
397  398    youngtrail95    youngtrail95@relay.cloud  2026-01-15 02:54:08
398  399     navyriver98     navyriver98@example.com  2024-01-31 20:40:01
399  400   livelyfield35  livelyfield35@hackstack.io  2025-03-31 22:48:29

[400 rows x 4 columns]

In [8]:
df_events

,id,url_id,user_id,event_type,timestamp,details
0,1,1,1,created,2025-02-15 09:17:02,"{""short_code"":""gl0NAL"",""original_url"":""https:/..."
1,2,2,92,created,2026-01-23 00:07:56,"{""short_code"":""dMfDz4"",""original_url"":""https:/..."
2,3,3,191,created,2026-02-20 19:53:02,"{""short_code"":""cAWBs3"",""original_url"":""https:/..."
3,4,4,145,created,2025-10-06 21:47:39,"{""short_code"":""txEiq2"",""original_url"":""https:/..."
4,5,5,13,created,2026-01-06 11:25:59,"{""short_code"":""kd950G"",""original_url"":""https:/..."
...,...,...,...,...,...,...
3417,3418,752,319,deleted,2025-01-24 05:29:45,"{""reason"":""duplicate""}"
3418,3419,511,290,deleted,2025-05-28 12:15:37,"{""reason"":""expired""}"
3419,3420,1892,329,deleted,2025-06-06 12:34:31,"{""reason"":""user_requested""}"
3420,3421,1702,150,deleted,2025-06-12 19:29:52,"{""reason"":""expired""}"
3421,3422,1661,385,deleted,2025-04-08 12:04:29,"{""reason"":""duplicate""}"

In [9]:
df_urls

,id,user_id,short_code,original_url,title,is_active,created_at,updated_at
0,1,1,gl0NAL,https://relay.cloud/cobalt/yard/1,Launch deck uplink,True,2025-02-15 09:17:02,2025-09-29 18:35:26
1,2,92,dMfDz4,https://hackstack.io/lively/engine/2,Incident notes trail,True,2026-01-23 00:07:56,2026-02-17 10:23:12
2,3,191,cAWBs3,https://opswise.net/gold/field/3,Ops review kernel,True,2026-02-20 19:53:02,2026-02-20 23:57:50
3,4,145,txEiq2,https://hackstack.io/keen/meadow/4,Status board orbit,True,2025-10-06 21:47:39,2025-12-23 08:31:57
4,5,13,kd950G,https://relay.cloud/rapid/journey/5,Ops review garden,True,2026-01-06 11:25:59,2026-01-07 18:47:32
...,...,...,...,...,...,...,...,...
1995,1996,157,KkKS5x,https://relay.cloud/ivory/signal/1996,Roadmap update field,True,2025-11-28 03:33:00,2026-01-10 18:18:53
1996,1997,247,mfUACz,https://opswise.net/mellow/network/1997,Incident notes network,True,2025-02-26 14:31:32,2026-01-09 10:09:19
1997,1998,7,OzVxna,https://relay.cloud/clear/zenith/1998,Status board network,True,2025-06-24 01:53:51,2025-12-20 21:35:52
1998,1999,248,cfuh4D,https://seeded.app/quiet/garden/1999,Status board network,True,2025-11-22 12:35:10,2026-02-05 04:20:56
1999,2000,158,HgBqSu,https://hackstack.io/calm/engine/2000,Demo link journey,True,2025-11-23 06:37:42,2026-01-26 18:36:09